name: EDHREC Decklist Scraper

on:
  schedule:
    - cron: "0 6 * * *"   # runs every day at 6 AM UTC
  workflow_dispatch:       # allows manual runs from the Actions tab

permissions:
  contents: write          # needed for git push to work

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python edhrec_scraper.py

      - name: Commit CSV outputs
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if ls *.csv 1> /dev/null 2>&1; then
            echo "CSV files found — committing updates."
            git add *.csv
            git commit -m "Update decklists $(date -u +'%Y-%m-%d')" || echo "No new changes to commit."
            git push
          else
            echo "No CSV files created — skipping commit."
          fi
