name: EDHREC Decklist Scraper
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # run daily at 6 AM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run scraper
        run: python edhrec_scraper.py

      - name: Commit CSV outputs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.csv || echo "No CSVs to add"
          git commit -m "Update optimized decks $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push
